### ISSUE TITLE
wrong git url

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/js-basics#1]
https://github.com/ga-wdi-boston/js-fundamentals-08

s/b

https://github.com/ga-wdi-boston/js-basics-1

**Comment by gaand** [comment]
Remove explicit reference to repo

**Comment by jrhorn424** [comment]
Sorry, what is `s/b`?

**Comment by gaand** [comment]
"Should be" but my comment make the change inapplicable.

**Comment by jrhorn424** [comment]
:+1:

**Comment by gaand** [comment]
Closed by 3110343e3e938b256490133e47cfbbc8eb914847 @gaand
