### ISSUE TITLE
Rename repository to node-js-basics

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/js-basics#16]
@gaand Thoughts?

**Comment by gaand** [comment]
It's about JavaScript the language, so as I remember our discussion, no.   Leave as js-basics.

**Comment by jrhorn424** [comment]
Ok, let's record this for the future.
- `js-` is for JavaScript qua language
- `node-` is for JavaScript in the node environment
- `browser-` is for JavaScript in the browser environment

If this is correct, I'll close this and track over at instructors.

**Comment by gaand** [comment]
Agreed.  I added it to the wiki.  Please edit as necessary.

**Comment by jrhorn424** [comment]
thanks @gaand
