### ISSUE TITLE
No reference to console.log

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/js-basics#18]
We don't actually reference "console.log" or what it does before we use it in our code along.

**Comment by payne-chris-r** [comment]
@jrhorn424 can you put eyes on the console.log section? I just realized I didn't follow proper github process flow when I first pulled this repo down and pushed to master instead of my own branch. Can you to take a look at what I wrote? On a side note: It would be very helpful for me to review git/github process flow with you as I haven't used git or github since last Summer and I want to make sure I'm getting this right at the start.

**Comment by gaand** [comment]
I view console.log as something that just is. It is not possible to start from first principals.
