### ISSUE TITLE
Double reference to //

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/js-basics#19]
In "falsy" section there are two references to comments "//" being falsy
0 // and -0
NaN
'' // and "" - the empty string

**Comment by gaand** [comment]
This are comment, meant to convey that the things commented out are that same thing as the thing preceding the comment.

**Comment by payne-chris-r** [comment]
Talked to Antony about this IRL. The // is his way of saying everything that comes after the 0 on line 1 and everything that comes after the '' on line 3 are both comments TO THE READER. This is NOT that comments in .js are treated as falsy.

**Comment by jrhorn424** [comment]
Since this is tracked in #20, I'm closing here. Thanks for discussing!
