### ISSUE TITLE
Two dependencies keys in package.json

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/js-basics#21]

**Comment by jrhorn424** [comment]
Fix by replacing the second value with the first and removing the extraneous key.

**Comment by gaand** [comment]
An artifact of merging in `node-template`?

**Comment by laurenfazah** [comment]
Fixed in latest merge from 013/master branch into master if you'd like to close @jrhorn424 @berziiii (not sure whom this belongs to).

**Comment by gaand** [comment]
I'm closing because the correction matches Jeff suggested fix.
