### ISSUE TITLE
Audit and update based on talk-template

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/js-basics#22]
In particular, there needs to be a preparation section.

The sections should match those in https://raw.githubusercontent.com/ga-wdi-boston/talk-template/master/README.md

There may be other changes needed, like the correct logo, license updates, and linter warnings.

**Comment by laurenfazah** [comment]
Fixed in latest merge from 013/master branch into master @jrhorn424. Ensured logo, license and linter warnings were up to date as well.
