### ISSUE TITLE
Discuss dates briefly when introducing variables using `bornOn`.

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/js-basics#23]
https://github.com/ga-wdi-boston/js-basics/commit/172985897140c902339f94fef6efb82bf237dace#diff-04c6e90faac2675aa89e2176d2eec7d8L88

This is a great example of institutional knowledge that was lost.

@gaand Had DOB as an example to talk about the fact that dates may be numbers to humans, but to programming languages, they're formatted strings.

This comes up throughout the program, and has pedagogical value being introduced so early. Details about date string parsing should not be covered, but the fact that dates are strings should be mentioned.

In addition to reverting this change, `dob` should become `born_on`.

@ga-wdi-boston/core

**Comment by gaand** [comment]
@jrhorn424 `born_on` or `bornOn`?

Also, maybe add as an additional resource a link to the Wikipedia entry on ISO 8601

**Comment by payne-chris-r** [comment]
I'm ok with whatever you guys decide on this. This was more of a goof on my end as far as lessons and personal instruction tools was concerned. Feel free to make an executive decision! I would agree with @gaand that it should be bornOn over born_on though. :-)

That said, I think `dob` is also fine now that I understand the significance.

**Comment by laurenfazah** [comment]
Fixed in latest merge from 013/master branch into master @jrhorn424 if you'd like to close. Changed `name` to `bornOn`.

**Comment by gaand** [comment]
I'm editing the title because I think we need more of a prompt to the consultant to talk about dates.

I suggest this as a start:  https://en.wikipedia.org/wiki/ISO_8601

**Comment by jrhorn424** [comment]
Please add a note to the README to discuss these points, @berziiii.

**Comment by jrhorn424** [comment]
@berziiii If you can, add notes about string formatting of dates to the README before tomorrow. If not, we'll get to it next time.

**Comment by jrhorn424** [comment]
<img width="597" alt="slack" src="https://cloud.githubusercontent.com/assets/388761/17893421/a0e2555e-6913-11e6-91fa-ea71bd06f3b1.png">
