### ISSUE TITLE
Add readline-sync as dependency

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/js-basics#27]

**Comment by austinc203** [comment]
@gaand says perhaps use node readline

**Comment by raq929** [comment]
Readline-sync added.  (PR #31)

**Comment by BenGitsCode** [comment]
This has come back to haunt us yet again, test this thoroughly before closing in 017's update.

**Comment by gaand** [comment]
I don't understand.  The pull was merged and includes the dependency.

**Comment by BenGitsCode** [comment]
I don't understand either, it may be an [installfest](https://github.com/ga-wdi-boston/orientation#installfest). Jeff thought he addressed this, as the PR shows, but half our developers needed to save the dependency manually.

**Comment by jrhorn424** [comment]
This is perplexing. Maybe 1.4.4 was a broken release. `^1.4.5` seems to work.

**Comment by jrhorn424** [comment]
Update to latest readline next iterations with `npm install --save readline-sync`.

@gaand Will this be obsolesced by #39?

**Comment by jrhorn424** [comment]
Wrong. It broke due to #45
