### ISSUE TITLE
Best practices for ++ operator

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/js-basics#30]
We're introducing the ++ operator in this section as follows: 
`let i;
i = 0;
i;
i = i + 1;
i;
i += 1;
i;
++i;
i;
i++;
i;`

I feel like there's more we should be saying about this, specifically that ++i and i++ don't do exactly the same thing. Is that outside the scope of this lesson?

**Comment by gaand** [comment]
No, just more than I write down.  I always discuss the differences between `++i` (increment `i` and evaluate to the incremented value) and `i++` (evaluate to the current value of `i` and then increment).  I guess I see it as implicit in `++i; i; i++; i;` (which doesn't mean it is).

**Comment by raq929** [comment]
Added a small section for clarity in 3a72252d5b930b22de30e615b2806559d01181c6.
