### ISSUE TITLE
ES6 is now ES2015

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/js-basics#35]
Update repo accordingly.

**Comment by BenGitsCode** [comment]
This is the incorrect ES reference. Should be ES6

```
 Some of the references in this document may include descriptions of ES2015 features.
```

**Comment by jrhorn424** [comment]
@BenGitsCode I think you have that exactly backwards?

**Comment by BenGitsCode** [comment]
You are correct, exactly backwards.

**Comment by jrhorn424** [comment]
Disregard recent comments. This is what is wrong as of this iteration. 

> (new in ECMAScript 6) 

Should be `(new in ECMAScript 2016)`.

I think I caught all references that started with ES, but may not have caught any that began with ECMA.

**Comment by gaand** [comment]
Should that be `2015`?
