### ISSUE TITLE
Rename variables in truthy/falsy section?

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/js-basics#36]
In 015 this led to some confusion about whether values or variables are truthy or falsy.

**Comment by jrhorn424** [comment]
I'd be in favor. This has lead to some confusion in the past as well (#20).

**Comment by payne-chris-r** [comment]
This should be resolved by the most recent commit. Changed to `truthyValue` and `falsyValue`. If ok, can you close @raq929 ?
