### ISSUE TITLE
Rename lead heading

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/js-basics#6]
<img width="702" alt="ga-wdi-boston_js-basics_-_javascript" src="https://cloud.githubusercontent.com/assets/388761/12398159/cdfdc60c-bddf-11e5-8fe1-33bf1a8397c1.png">

**Comment by gaand** [comment]
Remove 1.

**Comment by gaand** [comment]
Closed by 3110343e3e938b256490133e47cfbbc8eb914847 @gaand
