### ISSUE TITLE
Add more explicit demo/code along/lab

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/js-basics#7]
Nothing in the structure preventing it.

**Comment by jrhorn424** [comment]
Do you feel like this is addressed in #15? @gaand

**Comment by jrhorn424** [comment]
An additional lab was added in adc3333ef6757c81b00f43ed96cee1953454e267

**Comment by gaand** [comment]
@jrhorn424 I'm going to have to keepbetter track of notifications so I know when someone closes one of my issues sooner than 7 days after. :-P.

**Comment by jrhorn424** [comment]
Oh! Oops! Sorry @gaand. I really don't think it was intentional. I don't remember closing it. 😦
